### PR TITLE
fix:#86- styles in the categories section filter

### LINKED ISSUE #86: Styles In The Categories Section
### Explanation:

In [Artworks](https://art-marketplace.pages.dev/artworks/), when searching by filters, we have two lists: one of categories and another of types, a visual indication must be added to highlight which of the list items are currently selected.

### Screenshots:
Currently:
image

Should be:
image

### Checklist

 - [x] Remove underline in categories items
 - [x] Add background when some category is selected and change color to white
 - [x] Create and implement active state for the active item at filter list.
 
### References:
https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A2

### PR DESCRIPTION
**Pull request by arodriguezl9302**
### Description

Styles In The Categories Section Filter

### Proposal @Katsu08 @Israel-Laguan @e-azocar 
Due to the number of changes I made to complete this task, I propose that it be uploaded to EE2 

fixes #86 

#### Screenshots

image

image

#### Type of change

Bug fix (non-breaking change which fixes an issue)

### How to test it

If applicable, describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

1. Go to '/artworks?category=african-art&department=Japanese+Art&type=Manuscript'.

### Checklist:

- [x] Remove underline in categories items
- [x] Add background when some category is selected and change color to white
- [x] Create and implement active state for the active item at filter list.

### CODE REVIEW

**Review by e-azocar — APPROVED** [review]
Good work

File: src/components/ItemFilter.jsx [hunk 1]
```diff
@@ -0,0 +1,7 @@
+import React from 'react';
+
+export const ItemFilter = ({ item }) => {
+  return (
+    <div className='py-2 ml-2 cursor-pointer text-black hover:no-underline'>{item}</div>
+  );
+};
```
Comment (heliomar-pena) [inline src/components/ItemFilter.jsx]: ItemFilter and SelectedItemFilter could be just one React component, then you can do a condition on className to include the selected style

```suggestion
import React from 'react';

export const ItemFilter = ({ item, selectedDepartment }) => {
  const selectedStyles = SelectedDepartment === item ? {
    color: 'white',
    backgroundColor: '#11698E',
    padding: '5px',
  } : {};

  return (
    <div style={selectedStyles}  className='py-2 ml-2 cursor-pointer text-black hover:no-underline'>{item}</div>
  );
};
```

Then SelectedItemFilter can be removed

File: src/components/Products/Filters.jsx [hunk 2]
```diff
@@ -60,14 +64,16 @@ const Filters = ({
...
                 <div
                   key={department.id}
                   onClick={(e) => handleDepartment(e, department.en)}
-                  className="py-2 cursor-pointer text-black underline hover:no-underline"
                 >
-                  {department.es}
+                  {department.en === selectedDepartment
+                    ? <SelectedItemFilter item={department.es} />
+                    : <ItemFilter item={department.es} />
+                  }
```
Comment (heliomar-pena) [inline src/components/Products/Filters.jsx]: If you apply my changes, this condition is avoid and you can do:

```suggestion
                  <ItemFilter item={department.es} selectedDepartment={selectedDepartment} />
                  
```

Comment (heliomar-pena) [reply src/components/Products/Filters.jsx]: Same in other similar blocks of code

**Review by heliomar-pena — CHANGES_REQUESTED** [review]
Good job man! I left you some suggestions. The really important is about to unify the SelectedItemFilter logic in ItemFilter, to save lines of code and ease the implementation of this component in other places

File: src/components/ItemFilter.jsx (hunk 1 above)
Comment (arodriguezl9302) [reply src/components/ItemFilter.jsx]: @Katsu08 ok, I made some changes that I think improved a lot

File: src/components/Products/Filters.jsx (hunk 2 above)
Comment (arodriguezl9302) [reply src/components/Products/Filters.jsx]: ready

File: src/components/ItemFilter.jsx [hunk 3]
```diff
@@ -1,7 +1,16 @@
...
+export const ItemFilter = ({ element, selectedElement }) => {
+  const selectedStyles = selectedElement === element.en
+    ? {
+      color: 'white',
+      backgroundColor: '#11698E',
+      paddingLeft: '0.5rem',
+    }
+    : {
+      paddingLeft: '0.5rem',
+    };
```
Comment (heliomar-pena) [inline src/components/ItemFilter.jsx]: Since paddingLeft have the same value in both cases, paddingLeft 0.5rem can be moved to className.

You can use the TailwindCSS utilities class for this:

image

Comment (heliomar-pena) [inline src/components/ItemFilter.jsx]:
```suggestion
  const selectedStyles = selectedElement === element.en
    ? {
      color: 'white',
      backgroundColor: '#11698E',
    }
    : {};
```

File: src/components/ItemFilter.jsx [hunk 4]
```diff
@@ -1,7 +1,16 @@
...
   return (
-    <div className='py-2 ml-2 cursor-pointer text-black hover:no-underline'>{item}</div>
+    <div style={selectedStyles} className='py-2 cursor-pointer text-black hover:no-underline'>{element.es}</div>
```
Comment (heliomar-pena) [inline src/components/ItemFilter.jsx]: You can use the TailwindCSS utilities classes to define padding left size if item is active or if is not active, instead of handle it using style

Tailwind Classes | properties 
-- | --
pr-2 | padding-right: 0.5rem; /* 8px */
pb-2 | padding-bottom: 0.5rem; /* 8px */
pl-2 | padding-left: 0.5rem; /* 8px */



```suggestion
    <div style={selectedStyles} className='py-2 cursor-pointer text-black hover:no-underline pl-2'>{element.es}</div>
```

**Review by heliomar-pena — CHANGES_REQUESTED** [review]
Good work with the changes, now it looks so better!. I've left you some little comments

File: src/components/ItemFilter.jsx (hunk 1 above)
Comment (heliomar-pena) [reply src/components/ItemFilter.jsx]: @arodriguezl9302 Thanks man!

**Review by heliomar-pena — APPROVED** [review]
Good work!

**Review by Israel-Laguan — APPROVED** [review]
